// Kazakh Cyrillic alphabet (42 letters) with a Latin (2021 reform) toggle.
export type Letter = { cyr: string; latin: string };

export const ALPHABET: Letter[] = [
  { cyr: "А", latin: "A" },
  { cyr: "Ә", latin: "Á" },
  { cyr: "Б", latin: "B" },
  { cyr: "В", latin: "V" },
  { cyr: "Г", latin: "G" },
  { cyr: "Ғ", latin: "Ǵ" },
  { cyr: "Д", latin: "D" },
  { cyr: "Е", latin: "E" },
  { cyr: "Ё", latin: "Io" },
  { cyr: "Ж", latin: "J" },
  { cyr: "З", latin: "Z" },
  { cyr: "И", latin: "I" },
  { cyr: "Й", latin: "I" },
  { cyr: "К", latin: "K" },
  { cyr: "Қ", latin: "Q" },
  { cyr: "Л", latin: "L" },
  { cyr: "М", latin: "M" },
  { cyr: "Н", latin: "N" },
  { cyr: "Ң", latin: "Ń" },
  { cyr: "О", latin: "O" },
  { cyr: "Ө", latin: "Ó" },
  { cyr: "П", latin: "P" },
  { cyr: "Р", latin: "R" },
  { cyr: "С", latin: "S" },
  { cyr: "Т", latin: "T" },
  { cyr: "У", latin: "U" },
  { cyr: "Ұ", latin: "U" },
  { cyr: "Ү", latin: "Ú" },
  { cyr: "Ф", latin: "F" },
  { cyr: "Х", latin: "H" },
  { cyr: "Һ", latin: "H" },
  { cyr: "Ц", latin: "Ts" },
  { cyr: "Ч", latin: "Ch" },
  { cyr: "Ш", latin: "Sh" },
  { cyr: "Щ", latin: "Sch" },
  { cyr: "Ы", latin: "Y" },
  { cyr: "І", latin: "I" },
  { cyr: "Э", latin: "E" },
  { cyr: "Ю", latin: "Iu" },
  { cyr: "Я", latin: "Ia" },
  { cyr: "Ь", latin: "'" },
  { cyr: "Ъ", latin: "'" },
];
