// Generates 0002_seed.sql from the TS content files so seed never drifts.
import { readFileSync, writeFileSync } from "node:fs";

const vsrc = readFileSync(new URL("../src/content/vocab.ts", import.meta.url), "utf8");
const vocab = [...vsrc.matchAll(/\{\s*slug:\s*"([^"]+)",\s*kk:\s*"([^"]+)",\s*latin:\s*"([^"]+)",\s*en:\s*"([^"]+)",\s*category:\s*"([^"]+)"\s*\}/g)]
  .map((m) => ({ slug: m[1], kk: m[2], latin: m[3], en: m[4], category: m[5] }));

const bsrc = readFileSync(new URL("../src/content/badges.ts", import.meta.url), "utf8");
const badges = [...bsrc.matchAll(/\{\s*id:\s*"([^"]+)",\s*name:\s*"([^"]+)",\s*kk:\s*"([^"]+)",\s*symbol:\s*"([^"]+)",\s*hint:\s*"([^"]+)"\s*\}/g)]
  .map((m) => ({ id: m[1], name: m[2], kk: m[3], symbol: m[4], hint: m[5] }));

const esc = (s) => s.replace(/'/g, "''");

let out = "-- Auto-generated by scripts/gen-seed.mjs. Do not edit by hand.\n\n";
out += "insert into vocab (slug, kk, latin, en, category) values\n";
out += vocab.map((v) => `  ('${esc(v.slug)}', '${esc(v.kk)}', '${esc(v.latin)}', '${esc(v.en)}', '${esc(v.category)}')`).join(",\n");
out += "\non conflict (slug) do nothing;\n\n";

out += "insert into badges (id, name, kk, symbol, hint) values\n";
out += badges.map((b) => `  ('${esc(b.id)}', '${esc(b.name)}', '${esc(b.kk)}', '${esc(b.symbol)}', '${esc(b.hint)}')`).join(",\n");
out += "\non conflict (id) do nothing;\n";

writeFileSync(new URL("../supabase/migrations/0002_seed.sql", import.meta.url), out);
console.log(`Seed written: ${vocab.length} vocab, ${badges.length} badges.`);
