// Generates supabase/migrations/0007_seed_items.sql — one content_items row per
// question the games can ask — straight from the TS content files, so the table
// can never drift from what the app actually renders.
//
// Run:  node --experimental-strip-types scripts/gen-items.mjs
//
// Ids are derived, not generated: '<kind>:<ref_slug>:v<version>'. src/lib/items.ts
// computes the same id in the browser, which is what lets telemetry log an item
// reference offline with no lookup.
import { readFileSync, writeFileSync } from "node:fs";

const url = (p) => new URL(p, import.meta.url);

const { VOCAB } = await import(url("../src/content/vocab.ts"));
const { ALPHABET } = await import(url("../src/content/alphabet.ts"));
const { GREETINGS } = await import(url("../src/content/greetings.ts"));
const { PHRASES } = await import(url("../src/content/phrases.ts"));
const { REGIONS } = await import(url("../src/content/regions.ts"));
const { LETTER_AUDIO_SRC, KAZAKH_ONLY_LETTERS } = await import(
  url("../src/content/letter-audio.ts")
);
const { itemId, greetingSlug, CURRENT_VERSION } = await import(url("../src/lib/items.ts"));

const rows = [];

const push = (kind, refSlug, gameSlug, payload) => {
  rows.push({
    id: itemId(kind, refSlug),
    item_key: `${kind}:${refSlug}`,
    version: CURRENT_VERSION,
    kind,
    ref_slug: refSlug,
    game_slug: gameSlug,
    payload,
  });
};

// Vocab is shared across Word Match, Memory Match, Falling Words, Bazaar and
// Spotlight Panic, so it carries no game_slug.
for (const v of VOCAB) {
  push("vocab", v.slug, null, {
    kk: v.kk,
    latin: v.latin,
    en: v.en,
    category: v.category,
    image: `/img/${v.category}/${v.slug}.svg`,
    audio: `/audio/vocab/${v.slug}.mp3`,
  });
}

for (const l of ALPHABET) {
  push("letter", l.cyr, "sound-it-out", {
    cyr: l.cyr,
    latin: l.latin,
    audio: LETTER_AUDIO_SRC[l.cyr] ?? null,
    kazakh_only: KAZAKH_ONLY_LETTERS.includes(l.cyr),
  });
}

for (const g of GREETINGS) {
  push("greeting", greetingSlug(g.audio), "greetings-quiz", {
    kk: g.kk,
    en: g.en,
    latin: g.latin,
    audio: g.audio,
  });
}

for (const p of PHRASES) {
  push("phrase", p.kk, "story-maker", { kk: p.kk, en: p.en });
}

for (const r of REGIONS) {
  push("place", r.id, "where-kz", {
    name: r.name,
    kk: r.kk,
    category: r.category,
    x: r.x,
    y: r.y,
    fact: r.fact,
  });
}

const esc = (s) => String(s).replace(/'/g, "''");
const sqlText = (s) => (s === null || s === undefined ? "null" : `'${esc(s)}'`);
const sqlJson = (o) => `'${esc(JSON.stringify(o))}'::jsonb`;

let out = "-- Auto-generated by scripts/gen-items.mjs. Do not edit by hand.\n";
out += "-- Regenerate: node --experimental-strip-types scripts/gen-items.mjs\n\n";
out += "insert into content_items (id, item_key, version, kind, ref_slug, game_slug, payload, source, status) values\n";
out += rows
  .map(
    (r) =>
      `  (${sqlText(r.id)}, ${sqlText(r.item_key)}, ${r.version}, ${sqlText(r.kind)}, ` +
      `${sqlText(r.ref_slug)}, ${sqlText(r.game_slug)}, ${sqlJson(r.payload)}, 'seed', 'live')`,
  )
  .join(",\n");
out += "\non conflict (id) do update set\n";
out += "  payload = excluded.payload,\n";
out += "  game_slug = excluded.game_slug,\n";
out += "  item_key = excluded.item_key;\n";

const target = url("../supabase/migrations/0007_seed_items.sql");
writeFileSync(target, out);

const byKind = rows.reduce((acc, r) => ({ ...acc, [r.kind]: (acc[r.kind] ?? 0) + 1 }), {});
console.log(
  `Wrote ${rows.length} content items ->`,
  readFileSync(target, "utf8").length,
  "bytes\n",
  byKind,
);
